name: .NET MAUI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    env:
      Solution_Name: TrumpSuitGame.slnx
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore packages
      run: dotnet restore TrumpSuitGame.slnx

    - name: Decode PFX certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        [IO.File]::WriteAllBytes("TrumpSuitGame/signing.pfx", $pfx_cert_byte)
      shell: pwsh

    - name: Build MAUI MSIX
      run: |
        dotnet publish TrumpSuitGame/TrumpSuitGame.csproj `
          -f net10.0-windows10.0.26100.0 `
          -c $env:Configuration `
          -p:AppxPackageSigningEnabled=true `
          -p:PackageCertificateKeyFile="${{ github.workspace }}/TrumpSuitGame/signing.pfx" `
          -p:PackageCertificatePassword="${{ secrets.PFX_KEY }}"
      shell: pwsh

    - name: Clean up certificate
      run: Remove-Item -Path "TrumpSuitGame/signing.pfx" -Force
      shell: pwsh

    - name: Upload MSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSIX
        path: TrumpSuitGame/bin/Release/net10.0-windows10.0.26100.0/win10-x64/AppPackages
        include-hidden-files: true
        if-no-files-found: error
